version: '3.8'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=dashboard_admin
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_DB=dashboard-db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
